In [3]:
import numpy as np 

In [4]:
l = [[1,1], [2,2], [3, 5], [4, 5]]
l

[[1, 1], [2, 2], [3, 5], [4, 5]]

In [5]:
np_arr = np.array(l)
np_arr

array([[1, 1],
       [2, 2],
       [3, 5],
       [4, 5]])

In [6]:
type(l), type(np_arr)

(list, numpy.ndarray)

In [7]:
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]
lst3 = [9, 10, 11, 12]

merged = np.array([lst1, lst2, lst3])
merged

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
merged.shape

(3, 4)

In [9]:
merged[0]

array([1, 2, 3, 4])

In [10]:
merged[1][2]

7

In [12]:
merged[1:,2:]  #slicing

array([[ 7,  8],
       [11, 12]])

In [14]:
np.arange(8, 20)   # generates an array

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.ones((2, 4), dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
np.zeros((2, 4), dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.random.rand(2, 2)   # generates a random array

array([[0.87608942, 0.03062036],
       [0.03261355, 0.60425643]])

In [21]:
n = np.arange(10, 20)
n.reshape(2, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
np.random.randint(5, size=(2, 3))   # https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

array([[4, 3, 1],
       [3, 2, 2]])